name: Generate Common File

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  gen_common_file:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ALI_DNS:          223.5.5.5
      UPSTREAM_DNS:     127.0.0.1:54
      DIRECT_RULESET:   https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt

    steps:
      - name: Checkout the "master" branch of this repo
        uses: actions/checkout@v4
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Generated on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Download Contents
        run: |
          mkdir ./tmp
          wget ${{ env.DIRECT_RULESET }} -O ./tmp/raw_direct.txt


      - name: Process Contents
        run: |
          sed '/^#/d; ; /^IP-/d; /^PROCESS-NAME/d; /^DOMAIN-KEYWORD/d; s/DOMAIN,//g; s/DOMAIN-SUFFIX,//g; /^$/d' ./tmp/raw_direct.txt > ./tmp/list_direct.txt
          python3 script/remove_domains.py ./tmp/list_direct.txt ./customization/removed_domains.txt

      - name: Generate Common Files
        run: |
          cat ./customization/base_content.txt > ./result/agh_direct_alidns.txt
          (echo "" && cat ./tmp/list_direct.txt) >> ./result/agh_direct_alidns.txt
          cat ./customization/base_content.txt > ./result/agh_direct_updns.txt
          (echo "" && cat ./tmp/list_direct.txt) >>  ./result/agh_direct_updns.txt
          python3 script/gen_agh_file.py ./result/agh_direct_alidns.txt --dns ${{ env.ALI_DNS }}
          python3 script/gen_agh_file.py ./result/agh_direct_updns.txt --dns ${{ env.UPSTREAM_DNS }}

      - name: Remove Temporary Files
        run: |
          rm -rf ./tmp

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Generated on $(date +%Y%m%d%H%M)" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
