name: Generate Common File

on:
  schedule:
    - cron: '0 4 * * *'

  workflow_dispatch:

jobs:
  gen_common_file:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ALI_DNS:        223.5.5.5
      UPSTREAM_DNS:   127.0.0.1:54
      DIRECT_LIST:    https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt

    steps:
      - name: Checkout the "master" branch of this repo
        uses: actions/checkout@v4
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Generated on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Download Lists And Copy Lists
        run: |
          wget ${{ env.DIRECT_LIST }} -O ./result/agh_direct_alidns.txt
          cp -f ./result/agh_direct_alidns.txt ./result/agh_direct_updns.txt

      - name: Generate Common Files
        run: |
          python3 script/gen_agh_file.py ./result/agh_direct_alidns.txt --dns ${{ env.ALI_DNS }}
          python3 script/gen_agh_file.py ./result/agh_direct_updns.txt --dns ${{ env.UPSTREAM_DNS }}
          sed -i '1s/^/tls:\/\/8.8.4.4\ntls:\/\/1.0.0.1\n\[\/lan\/\]127\.0\.0\.1:54\n\[\/\/\]127\.0\.0\.1:54\n/' ./result/agh_direct_alidns.txt
          sed -i '1s/^/tls:\/\/8.8.4.4\ntls:\/\/1.0.0.1\n/\[\/lan\/\]127\.0\.0\.1:54\n\[\/\/\]127\.0\.0\.1:54\n' ./result/agh_direct_updns.txt

      # - name: Release and upload assets
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: ${{ env.RELEASE_NAME }}
      #     tag_name: ${{ env.TAG_NAME }}
      #     draft: false
      #     prerelease: false
      #     files: |
      #       ./configuration/release/sr_ark.conf
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Generated on $(date +%Y%m%d%H%M)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
